import { MigrationInterface, QueryRunner } from "typeorm";

export class FixUUIDBatchMappings1777709946458 implements MigrationInterface {
    name = 'FixUUIDBatchMappings1777709946458'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`admission_leads\` CHANGE \`parent_name\` \`parent_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`admission_leads\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`admission_leads\` CHANGE \`course_interest\` \`course_interest\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`admission_leads\` CHANGE \`remarks\` \`remarks\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP FOREIGN KEY \`FK_a6b4c8350fe376acb04b178f202\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` CHANGE \`lead_id\` \`lead_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`academic_sessions\` CHANGE \`start_date\` \`start_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`academic_sessions\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`relation\` \`relation\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`occupation\` \`occupation\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`address\` \`address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`roll_no\` \`roll_no\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`last_name\` \`last_name\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`gender\` \`gender\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`dob\` \`dob\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`address\` \`address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`batch_students\` CHANGE \`joined_on\` \`joined_on\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` DROP FOREIGN KEY \`FK_314e747891d5555efc344bd2887\``);
        await queryRunner.query(`ALTER TABLE \`enrollments\` CHANGE \`batch_id\` \`batch_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP FOREIGN KEY \`FK_a0490337d2e5b8aed63a4701c3f\``);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP FOREIGN KEY \`FK_dbc9dbab0eddd33834beeeb4d7d\``);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP FOREIGN KEY \`FK_c333b8c19525fc0a855ff8c3082\``);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP FOREIGN KEY \`FK_271089b0c13ec85177e2fbb9606\``);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP COLUMN \`institute_id\``);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD \`institute_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP COLUMN \`branch_id\``);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD \`branch_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP COLUMN \`course_id\``);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD \`course_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP COLUMN \`session_id\``);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD \`session_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` CHANGE \`batch_mode\` \`batch_mode\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` CHANGE \`start_date\` \`start_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` CHANGE \`end_date\` \`end_date\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` CHANGE \`capacity\` \`capacity\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP FOREIGN KEY \`FK_8b847abe999e5e85476fae8f05b\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP FOREIGN KEY \`FK_9ebbe67dc162b7cd815d3c091b7\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP FOREIGN KEY \`FK_6771eaca94f3b321050b4bff834\``);
        await queryRunner.query(`DROP INDEX \`IDX_e8b65c30a036f6785c753ab92d\` ON \`batch_teachers\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP COLUMN \`batch_id\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD \`batch_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP COLUMN \`teacher_id\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD \`teacher_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP COLUMN \`subject_id\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD \`subject_id\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` CHANGE \`assigned_on\` \`assigned_on\` date NULL`);
        await queryRunner.query(`ALTER TABLE \`subjects\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`description\` \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`duration\` \`duration\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`code\` \`code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`address\` \`address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`state\` \`state\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`code\` \`code\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`website\` \`website\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`logo_url\` \`logo_url\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`address\` \`address\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`city\` \`city\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`state\` \`state\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL`);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`phone\` \`phone\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`email\` \`email\` varchar(255) NULL`);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`qualification\` \`qualification\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`joining_date\` \`joining_date\` date NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_e8b65c30a036f6785c753ab92d\` ON \`batch_teachers\` (\`batch_id\`, \`teacher_id\`, \`subject_id\`)`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD CONSTRAINT \`FK_a6b4c8350fe376acb04b178f202\` FOREIGN KEY (\`lead_id\`) REFERENCES \`admission_leads\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` ADD CONSTRAINT \`FK_314e747891d5555efc344bd2887\` FOREIGN KEY (\`batch_id\`) REFERENCES \`batches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD CONSTRAINT \`FK_a0490337d2e5b8aed63a4701c3f\` FOREIGN KEY (\`institute_id\`) REFERENCES \`institutes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD CONSTRAINT \`FK_dbc9dbab0eddd33834beeeb4d7d\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD CONSTRAINT \`FK_c333b8c19525fc0a855ff8c3082\` FOREIGN KEY (\`course_id\`) REFERENCES \`courses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD CONSTRAINT \`FK_271089b0c13ec85177e2fbb9606\` FOREIGN KEY (\`session_id\`) REFERENCES \`academic_sessions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD CONSTRAINT \`FK_8b847abe999e5e85476fae8f05b\` FOREIGN KEY (\`batch_id\`) REFERENCES \`batches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD CONSTRAINT \`FK_9ebbe67dc162b7cd815d3c091b7\` FOREIGN KEY (\`teacher_id\`) REFERENCES \`teachers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD CONSTRAINT \`FK_6771eaca94f3b321050b4bff834\` FOREIGN KEY (\`subject_id\`) REFERENCES \`subjects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP FOREIGN KEY \`FK_6771eaca94f3b321050b4bff834\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP FOREIGN KEY \`FK_9ebbe67dc162b7cd815d3c091b7\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP FOREIGN KEY \`FK_8b847abe999e5e85476fae8f05b\``);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP FOREIGN KEY \`FK_271089b0c13ec85177e2fbb9606\``);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP FOREIGN KEY \`FK_c333b8c19525fc0a855ff8c3082\``);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP FOREIGN KEY \`FK_dbc9dbab0eddd33834beeeb4d7d\``);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP FOREIGN KEY \`FK_a0490337d2e5b8aed63a4701c3f\``);
        await queryRunner.query(`ALTER TABLE \`enrollments\` DROP FOREIGN KEY \`FK_314e747891d5555efc344bd2887\``);
        await queryRunner.query(`ALTER TABLE \`admissions\` DROP FOREIGN KEY \`FK_a6b4c8350fe376acb04b178f202\``);
        await queryRunner.query(`DROP INDEX \`IDX_e8b65c30a036f6785c753ab92d\` ON \`batch_teachers\``);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`joining_date\` \`joining_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`qualification\` \`qualification\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`teachers\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`state\` \`state\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`city\` \`city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`address\` \`address\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`logo_url\` \`logo_url\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`website\` \`website\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`institutes\` CHANGE \`code\` \`code\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`state\` \`state\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`city\` \`city\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`address\` \`address\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`branches\` CHANGE \`code\` \`code\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`duration\` \`duration\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`courses\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`subjects\` CHANGE \`description\` \`description\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` CHANGE \`assigned_on\` \`assigned_on\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP COLUMN \`subject_id\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD \`subject_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP COLUMN \`teacher_id\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD \`teacher_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` DROP COLUMN \`batch_id\``);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD \`batch_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_e8b65c30a036f6785c753ab92d\` ON \`batch_teachers\` (\`batch_id\`, \`teacher_id\`, \`subject_id\`)`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD CONSTRAINT \`FK_6771eaca94f3b321050b4bff834\` FOREIGN KEY (\`subject_id\`) REFERENCES \`subjects\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD CONSTRAINT \`FK_9ebbe67dc162b7cd815d3c091b7\` FOREIGN KEY (\`teacher_id\`) REFERENCES \`teachers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batch_teachers\` ADD CONSTRAINT \`FK_8b847abe999e5e85476fae8f05b\` FOREIGN KEY (\`batch_id\`) REFERENCES \`batches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batches\` CHANGE \`capacity\` \`capacity\` int NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`batches\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`batches\` CHANGE \`start_date\` \`start_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`batches\` CHANGE \`batch_mode\` \`batch_mode\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP COLUMN \`session_id\``);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD \`session_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP COLUMN \`course_id\``);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD \`course_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP COLUMN \`branch_id\``);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD \`branch_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` DROP COLUMN \`institute_id\``);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD \`institute_id\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD CONSTRAINT \`FK_271089b0c13ec85177e2fbb9606\` FOREIGN KEY (\`session_id\`) REFERENCES \`academic_sessions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD CONSTRAINT \`FK_c333b8c19525fc0a855ff8c3082\` FOREIGN KEY (\`course_id\`) REFERENCES \`courses\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD CONSTRAINT \`FK_dbc9dbab0eddd33834beeeb4d7d\` FOREIGN KEY (\`branch_id\`) REFERENCES \`branches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batches\` ADD CONSTRAINT \`FK_a0490337d2e5b8aed63a4701c3f\` FOREIGN KEY (\`institute_id\`) REFERENCES \`institutes\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` CHANGE \`batch_id\` \`batch_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`enrollments\` ADD CONSTRAINT \`FK_314e747891d5555efc344bd2887\` FOREIGN KEY (\`batch_id\`) REFERENCES \`batches\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`batch_students\` CHANGE \`joined_on\` \`joined_on\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`address\` \`address\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`dob\` \`dob\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`gender\` \`gender\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`last_name\` \`last_name\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`roll_no\` \`roll_no\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`students\` CHANGE \`user_id\` \`user_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`address\` \`address\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`occupation\` \`occupation\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`phone\` \`phone\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`student_guardians\` CHANGE \`relation\` \`relation\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`academic_sessions\` CHANGE \`end_date\` \`end_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`academic_sessions\` CHANGE \`start_date\` \`start_date\` date NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`admissions\` CHANGE \`lead_id\` \`lead_id\` varchar(36) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`admissions\` ADD CONSTRAINT \`FK_a6b4c8350fe376acb04b178f202\` FOREIGN KEY (\`lead_id\`) REFERENCES \`admission_leads\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`admission_leads\` CHANGE \`remarks\` \`remarks\` text NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`admission_leads\` CHANGE \`course_interest\` \`course_interest\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`admission_leads\` CHANGE \`email\` \`email\` varchar(255) NULL DEFAULT 'NULL'`);
        await queryRunner.query(`ALTER TABLE \`admission_leads\` CHANGE \`parent_name\` \`parent_name\` varchar(255) NULL DEFAULT 'NULL'`);
    }

}
