import { MigrationInterface, QueryRunner } from "typeorm";

export class RELATION1777882693358 implements MigrationInterface {
    name = 'RELATION1777882693358'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`class_rooms\` (\`id\` int NOT NULL AUTO_INCREMENT, \`branch_id\` int NOT NULL, \`room_name\` varchar(255) NOT NULL, \`room_code\` varchar(50) NULL, \`capacity\` int NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`timetable_slots\` (\`id\` int NOT NULL AUTO_INCREMENT, \`branch_id\` int NOT NULL, \`slot_name\` varchar(100) NOT NULL, \`start_time\` time NOT NULL, \`end_time\` time NOT NULL, \`is_break_slot\` tinyint NOT NULL DEFAULT 0, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`timetables\` (\`id\` int NOT NULL AUTO_INCREMENT, \`batch_id\` int NOT NULL, \`subject_id\` int NOT NULL, \`teacher_id\` int NOT NULL, \`branch_id\` int NOT NULL, \`session_id\` int NOT NULL, \`class_room_id\` int NOT NULL, \`slot_id\` int NOT NULL, \`day_of_week\` enum ('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') NOT NULL, \`start_time\` time NULL, \`end_time\` time NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`live_classes\` (\`id\` int NOT NULL AUTO_INCREMENT, \`batch_id\` int NOT NULL, \`subject_id\` int NOT NULL, \`teacher_id\` int NOT NULL, \`branch_id\` int NOT NULL, \`session_id\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`join_url\` text NULL, \`start_datetime\` datetime NOT NULL, \`end_datetime\` datetime NOT NULL, \`recording_url\` text NULL, \`status\` enum ('scheduled', 'ongoing', 'completed', 'cancelled') NOT NULL DEFAULT 'scheduled', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`live_class_participants\` (\`id\` int NOT NULL AUTO_INCREMENT, \`live_class_id\` int NOT NULL, \`user_id\` int NOT NULL, \`joined_at\` datetime NULL, \`left_at\` datetime NULL, \`attendance_status\` enum ('present', 'absent') NOT NULL DEFAULT 'absent', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attendance_sessions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`batch_id\` int NOT NULL, \`subject_id\` int NOT NULL, \`teacher_id\` int NOT NULL, \`branch_id\` int NOT NULL, \`session_id\` int NOT NULL, \`attendance_date\` date NOT NULL, \`live_class_id\` int NULL, \`status\` enum ('draft', 'published') NOT NULL DEFAULT 'draft', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`attendance_records\` (\`id\` int NOT NULL AUTO_INCREMENT, \`attendance_session_id\` int NOT NULL, \`student_id\` int NOT NULL, \`attendance_status\` enum ('present', 'absent', 'late', 'excused') NOT NULL, \`remarks\` text NULL, \`marked_by_user_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`leave_requests\` (\`id\` int NOT NULL AUTO_INCREMENT, \`student_id\` int NOT NULL, \`from_date\` date NOT NULL, \`to_date\` date NOT NULL, \`reason\` text NULL, \`approval_status\` enum ('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending', \`approved_by_user_id\` int NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`materials\` (\`id\` int NOT NULL AUTO_INCREMENT, \`subject_id\` int NOT NULL, \`teacher_id\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`material_type\` enum ('pdf', 'video', 'document', 'link', 'other') NOT NULL DEFAULT 'other', \`file_url\` text NULL, \`video_url\` text NULL, \`status\` enum ('active', 'inactive') NOT NULL DEFAULT 'active', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`material_batch_maps\` (\`id\` int NOT NULL AUTO_INCREMENT, \`material_id\` int NOT NULL, \`batch_id\` int NOT NULL, \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`assignments\` (\`id\` int NOT NULL AUTO_INCREMENT, \`batch_id\` int NOT NULL, \`subject_id\` int NOT NULL, \`teacher_id\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NULL, \`assigned_date\` date NULL, \`due_date\` date NOT NULL, \`max_marks\` int NULL, \`status\` enum ('draft', 'published', 'closed') NOT NULL DEFAULT 'draft', \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`assignment_submissions\` (\`id\` int NOT NULL AUTO_INCREMENT, \`assignment_id\` int NOT NULL, \`student_id\` int NOT NULL, \`submission_text\` text NULL, \`file_url\` text NULL, \`submitted_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`marks_awarded\` decimal(5,2) NULL, \`feedback_text\` text NULL, \`status\` enum ('pending', 'graded', 'resubmission_requested') NOT NULL DEFAULT 'pending', \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE \`assignment_submissions\``);
        await queryRunner.query(`DROP TABLE \`assignments\``);
        await queryRunner.query(`DROP TABLE \`material_batch_maps\``);
        await queryRunner.query(`DROP TABLE \`materials\``);
        await queryRunner.query(`DROP TABLE \`leave_requests\``);
        await queryRunner.query(`DROP TABLE \`attendance_records\``);
        await queryRunner.query(`DROP TABLE \`attendance_sessions\``);
        await queryRunner.query(`DROP TABLE \`live_class_participants\``);
        await queryRunner.query(`DROP TABLE \`live_classes\``);
        await queryRunner.query(`DROP TABLE \`timetables\``);
        await queryRunner.query(`DROP TABLE \`timetable_slots\``);
        await queryRunner.query(`DROP TABLE \`class_rooms\``);
    }

}
